name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Files
        run: ls -la

      - name: Python Version
        run: python --version

      - name: Run Application
        run: python app.py
